package org.example.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.example.dataobject.UserPasswordDO;
import org.example.dataobject.UserPasswordDOExample;
import org.springframework.stereotype.Repository;

@Repository
public interface UserPasswordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_PASSWORD
     *
     * @mbg.generated Fri Apr 24 15:56:03 CST 2020
     */
    long countByExample(UserPasswordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_PASSWORD
     *
     * @mbg.generated Fri Apr 24 15:56:03 CST 2020
     */
    int deleteByExample(UserPasswordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_PASSWORD
     *
     * @mbg.generated Fri Apr 24 15:56:03 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_PASSWORD
     *
     * @mbg.generated Fri Apr 24 15:56:03 CST 2020
     */
    int insert(UserPasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_PASSWORD
     *
     * @mbg.generated Fri Apr 24 15:56:03 CST 2020
     */
    int insertSelective(UserPasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_PASSWORD
     *
     * @mbg.generated Fri Apr 24 15:56:03 CST 2020
     */
    List<UserPasswordDO> selectByExample(UserPasswordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_PASSWORD
     *
     * @mbg.generated Fri Apr 24 15:56:03 CST 2020
     */
    UserPasswordDO selectByPrimaryKey(Integer id);

    UserPasswordDO selectByUserId(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_PASSWORD
     *
     * @mbg.generated Fri Apr 24 15:56:03 CST 2020
     */
    int updateByExampleSelective(@Param("record") UserPasswordDO record, @Param("example") UserPasswordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_PASSWORD
     *
     * @mbg.generated Fri Apr 24 15:56:03 CST 2020
     */
    int updateByExample(@Param("record") UserPasswordDO record, @Param("example") UserPasswordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_PASSWORD
     *
     * @mbg.generated Fri Apr 24 15:56:03 CST 2020
     */
    int updateByPrimaryKeySelective(UserPasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_PASSWORD
     *
     * @mbg.generated Fri Apr 24 15:56:03 CST 2020
     */
    int updateByPrimaryKey(UserPasswordDO record);
}