package org.example.dataobject;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table USER_INFO
 *
 * @mbg.generated do_not_delete_during_merge Fri Apr 24 15:56:03 CST 2020
 */
public class UserDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_INFO.ID
     *
     * @mbg.generated Fri Apr 24 15:56:03 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_INFO.NAME
     *
     * @mbg.generated Fri Apr 24 15:56:03 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_INFO.GENDER
     *
     * @mbg.generated Fri Apr 24 15:56:03 CST 2020
     */
    private Integer gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_INFO.AGE
     *
     * @mbg.generated Fri Apr 24 15:56:03 CST 2020
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_INFO.TELPHONE
     *
     * @mbg.generated Fri Apr 24 15:56:03 CST 2020
     */
    private Integer telphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_INFO.REGISTER_MODE
     *
     * @mbg.generated Fri Apr 24 15:56:03 CST 2020
     */
    private String registerMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_INFO.THIRD_PARTY_ID
     *
     * @mbg.generated Fri Apr 24 15:56:03 CST 2020
     */
    private String thirdPartyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_INFO.ID
     *
     * @return the value of USER_INFO.ID
     *
     * @mbg.generated Fri Apr 24 15:56:03 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_INFO.ID
     *
     * @param id the value for USER_INFO.ID
     *
     * @mbg.generated Fri Apr 24 15:56:03 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_INFO.NAME
     *
     * @return the value of USER_INFO.NAME
     *
     * @mbg.generated Fri Apr 24 15:56:03 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_INFO.NAME
     *
     * @param name the value for USER_INFO.NAME
     *
     * @mbg.generated Fri Apr 24 15:56:03 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_INFO.GENDER
     *
     * @return the value of USER_INFO.GENDER
     *
     * @mbg.generated Fri Apr 24 15:56:03 CST 2020
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_INFO.GENDER
     *
     * @param gender the value for USER_INFO.GENDER
     *
     * @mbg.generated Fri Apr 24 15:56:03 CST 2020
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_INFO.AGE
     *
     * @return the value of USER_INFO.AGE
     *
     * @mbg.generated Fri Apr 24 15:56:03 CST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_INFO.AGE
     *
     * @param age the value for USER_INFO.AGE
     *
     * @mbg.generated Fri Apr 24 15:56:03 CST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_INFO.TELPHONE
     *
     * @return the value of USER_INFO.TELPHONE
     *
     * @mbg.generated Fri Apr 24 15:56:03 CST 2020
     */
    public Integer getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_INFO.TELPHONE
     *
     * @param telphone the value for USER_INFO.TELPHONE
     *
     * @mbg.generated Fri Apr 24 15:56:03 CST 2020
     */
    public void setTelphone(Integer telphone) {
        this.telphone = telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_INFO.REGISTER_MODE
     *
     * @return the value of USER_INFO.REGISTER_MODE
     *
     * @mbg.generated Fri Apr 24 15:56:03 CST 2020
     */
    public String getRegisterMode() {
        return registerMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_INFO.REGISTER_MODE
     *
     * @param registerMode the value for USER_INFO.REGISTER_MODE
     *
     * @mbg.generated Fri Apr 24 15:56:03 CST 2020
     */
    public void setRegisterMode(String registerMode) {
        this.registerMode = registerMode == null ? null : registerMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_INFO.THIRD_PARTY_ID
     *
     * @return the value of USER_INFO.THIRD_PARTY_ID
     *
     * @mbg.generated Fri Apr 24 15:56:03 CST 2020
     */
    public String getThirdPartyId() {
        return thirdPartyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_INFO.THIRD_PARTY_ID
     *
     * @param thirdPartyId the value for USER_INFO.THIRD_PARTY_ID
     *
     * @mbg.generated Fri Apr 24 15:56:03 CST 2020
     */
    public void setThirdPartyId(String thirdPartyId) {
        this.thirdPartyId = thirdPartyId == null ? null : thirdPartyId.trim();
    }
}